title: Le Na Hoang
logo: Head Shot - Le Na Hoang.JPEG
theme: jekyll-theme-minimal

# CONTACT

*Thank you for visiting my engineering portfolio. I'm always excited to connect with fellow engineers, researchers, recruiters, and industry professionals.*

<table>
<tbody>

<tr>
<td>📧</td>
<td><a href="mailto:">Lenaforwork33@gmail.com</a></td>
</tr>

<tr>
<td>🎓</td>
<td>Embry-Riddle Aeronautical University</td>
</tr>

<tr>
<td>📍</td>
<td>Daytona Beach, Florida, USA</td>
</tr>

<tr>
<td>📄</td>
<td><a href="Resume.pdf">Download Resume</a></td>
</tr>

<tr>
<td>💼</td>
<td><a href="YOUR_LINKEDIN">https://www.linkedin.com/in/le-na-hoang/</a></td>
</tr>

<tr>
<td>💻</td>
<td><a href="YOUR_GITHUB">GitHub</a></td>
</tr>

</tbody>
</table>
